# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "inverter-unstable-${version}";
  version = "2019-03-04";
  rev = "7a2b394d232a34b2eff75426350e980eb137e629";

  goPackagePath = "github.com/ardaxi/inverter";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/ArdaXi/inverter.git";
    sha256 = "1cahhvfmd0mi8q0ll75yqmpar1p6w9lpmap3kr89j8k3j5r4iajr";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
