# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "inverter-unstable-${version}";
  version = "2019-03-04";
  rev = "a8c2d8d4a3cc9f7f34c851a105c0a3de0c913561";

  goPackagePath = "github.com/ardaxi/inverter";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/ArdaXi/inverter.git";
    sha256 = "0iknp75kr92apxkf4lp66jx60m3izmy9vz5gvjfh100ymvijwbjw";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
