# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "inverter-unstable-${version}";
  version = "2019-03-04";
  rev = "18b565a7fad4bc245afcfbeec76b64777cef1691";

  goPackagePath = "github.com/ardaxi/inverter";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/ArdaXi/inverter.git";
    sha256 = "1rpdnarlvknlpd7fwyc876wchjf95s9wzjipksyn167j7786gqk2";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
