# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/beorn7/perks";
    fetch = {
      type = "git";
      url = "https://github.com/beorn7/perks";
      rev = "3a771d992973f24aa725d07868b467d1ddfceafb";
      sha256 = "1l2lns4f5jabp61201sh88zf3b0q793w4zdgp9nll7mmfcxxjif3";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "b5d812f8a3706043e23a9cd5babf2e5423744d30";
      sha256 = "15am4s4646qy6iv0g3kkqq52rzykqjhm4bf08dk0fy2r58knpsyl";
    };
  }
  {
    goPackagePath = "github.com/matttproud/golang_protobuf_extensions";
    fetch = {
      type = "git";
      url = "https://github.com/matttproud/golang_protobuf_extensions";
      rev = "c182affec369e30f25d3eb8cd8a478dee585ae7d";
      sha256 = "1xqsf9vpcrd4hp95rl6kgmjvkv1df4aicfw4l5vfcxcwxknfx2xs";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_golang";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_golang";
      rev = "2daed26f633ce23fab5efc02fb3f2e803b3526c3";
      sha256 = "0j5hgwr002kns9wmcb3akj20xnb2xn7jwvrv5viciwhkimyb0qak";
    };
  }
  {
    goPackagePath = "github.com/prometheus/client_model";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/client_model";
      rev = "fd36f4220a901265f90734c3183c5f0c91daa0b8";
      sha256 = "1bs5d72k361llflgl94c22n0w53j30rsfh84smgk8mbjbcmjsaa5";
    };
  }
  {
    goPackagePath = "github.com/prometheus/common";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/common";
      rev = "7a3416fd1f41341905f138746c51a5092e7ddf7a";
      sha256 = "12lcdbi4kf1bl4hv9vkadhcsyrpzzvn6g8g5kgiqqi6yhqzwb33q";
    };
  }
  {
    goPackagePath = "github.com/prometheus/procfs";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/procfs";
      rev = "bbced9601137e764853b2fad7ec3e2dc4c504e02";
      sha256 = "0fncixicvykhx12qcflb3j9hyhqhzzdi05j80zwjl0p97w47h26i";
    };
  }
]
