# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "inverter-unstable-${version}";
  version = "2019-03-04";
  rev = "0a26f185d1d6368edda7a2cc00996a3a4a8fb63d";

  goPackagePath = "github.com/ardaxi/inverter";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/ArdaXi/inverter.git";
    sha256 = "1xkrxqq4b504xslypx9l248cr2rjk38hph328cdw9jdybw487b25";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
