# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "prometheus-postgresql-adapter-unstable-${version}";
  version = "2018-08-22";
  rev = "a84adc57061fdddc327b6fdda9f836c668310123";

  goPackagePath = "github.com/timescale/prometheus-postgresql-adapter";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/timescale/prometheus-postgresql-adapter";
    sha256 = "05wa64n3j8yc57j6lbgjfj60ih4xg8dc9x4f4paj41pfni1mgi5l";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
